# Generated by Django 6.0.7 on 2026-08-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_scanresult_delete_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('feature_vector', models.CharField(max_length=100)),
                ('rf_predicted_risk', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('verified_risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
